#!/usr/bin/env python
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate the `demo/` directory.

Everything in `demo/` is produced by this script, so the numbers quoted in
`demo/README.md` are always the numbers the current build produces::

    python examples/make_demo.py [--fast]

Two systems are prepared and docked:

* **3PTB** — benzamidine in bovine trypsin. Small, rigid-ish and fast; this is
  the *accuracy* benchmark (the top pose must reproduce the crystal pose).
* **1M17** — erlotinib in the EGFR kinase domain. A genuinely three-dimensional,
  flexible drug (29 heavy atoms, 11 rotatable bonds) that exercises the nested
  torsion tree.

Plus a ligand built from nothing but a SMILES string, to show the preparation
pipeline producing three-dimensional coordinates on demand.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
for p in (ROOT / "python", ROOT / "tests"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

import odock  # noqa: E402
from redock import redock  # noqa: E402

#: 6,7-bis(2-methoxyethoxy)-N-(3-ethynylphenyl)quinazolin-4-amine (erlotinib).
ERLOTINIB = "COCCOc1cc2c(cc1OCCOC)ncnc2Nc3cccc(c3)C#C"

#: A three-dimensional, drug-like ligand used to demonstrate `prepare_ligand`.
DEMO_SMILES = "CCOC(=O)N1CCC(CC1)Oc1ccc(NC(=O)C)cc1"
DEMO_NAME = "demo-ligand"


def _utf8_streams() -> None:
    """Make the console able to print the units this script reports.

    The box is printed with Ångström signs.  On a Windows console whose code
    page is not UTF-8 Python encodes stdout with GBK or cp1252, and `print`
    raises `UnicodeEncodeError`, turning the documented regeneration command
    into a crash before it docks anything.  `odock`'s own CLI reconfigures the
    same two streams for exactly this reason; reconfiguring is harmless where
    the console is already UTF-8.
    """
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is None:
            continue
        try:
            reconfigure(encoding="utf-8", errors="replace")
        except (ValueError, OSError):  # pragma: no cover - stream replaced
            pass


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outdir", default=str(ROOT / "demo"))
    ap.add_argument("--fast", action="store_true", help="fewer Monte-Carlo runs")
    args = ap.parse_args(argv)

    _utf8_streams()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    exhaustive = 4 if args.fast else 16
    notes: list[str] = []

    # ------------------------------------------------------------------ 3PTB
    print("=" * 72)
    print("3PTB — benzamidine in bovine trypsin (accuracy benchmark)")
    print("=" * 72)
    trypsin = redock(
        ROOT / "tests" / "data" / "3PTB.pdb",
        "BEN",
        exhaustiveness=exhaustive,
        seed=42,
        outdir=outdir / "3ptb",
    )

    print(trypsin.table())
    print(trypsin.summary())

    # ------------------------------------------------------------------ 1M17
    print()
    print("=" * 72)
    print("1M17 — erlotinib in the EGFR kinase domain (flexible, drug-like)")
    print("=" * 72)
    egfr = redock(
        ROOT / "tests" / "data" / "1M17.pdb",
        "AQ4",
        smiles=ERLOTINIB,
        exhaustiveness=exhaustive,
        seed=42,
        buffer=4.0,
        outdir=outdir / "egfr",
    )
    print(egfr.table())
    print(egfr.summary())

    # ------------------------------------------------- a ligand from SMILES
    print()
    print("=" * 72)
    print(f"A three-dimensional ligand built from SMILES only ({DEMO_NAME})")
    print("=" * 72)
    mol, text, report = odock.prepare_ligand(
        DEMO_SMILES, outdir / "ligand_from_smiles.pdbqt", name=DEMO_NAME
    )
    print(f"  {report.summary()}")
    (outdir / "ligand_from_smiles.smi").write_text(DEMO_SMILES + "\n", encoding="utf-8")
    print(f"  wrote {outdir / 'ligand_from_smiles.pdbqt'}")

    # ------------------------------------------------------------------ notes
    egfr_rows = sorted(r[1] for r in egfr.poses)[:4]
    summary = (
        "| system | ligand | heavy atoms | N_tors | top-pose RMSD | best RMSD "
        "within 1 kcal/mol |\n"
        "|---|---|---|---|---|---|\n"
        f"| 3PTB (trypsin) | benzamidine | {trypsin.num_atoms} | "
        f"{trypsin.num_tors:g} | **{trypsin.best_rmsd:.2f} Å** | "
        f"{trypsin.closest_within():.2f} Å |\n"
        f"| 1M17 (EGFR) | erlotinib | {egfr.num_atoms} | {egfr.num_tors:g} | "
        f"{egfr.best_rmsd:.2f} Å | **{egfr.closest_within():.2f} Å** |\n"
    )
    readme = f"""# OpenDocking demo

Everything here is regenerated by

```bash
python examples/make_demo.py
```

so the numbers below are whatever the current build produces; nothing is
hand-edited. The structures are the crystal coordinates of the two PDB entries,
prepared with `odock prepare`.

## Re-docking results

{summary}
`RMSD` is the heavy-atom RMSD against the experimental pose, with **no**
superposition: the docking had to find the crystal pose in the same reference
frame. The last column is the standard "top-N" measure — the best RMSD among
all poses within 1 kcal/mol of the top score. It exists because for a flexible
ligand the *ranking* of near-degenerate poses is not meaningful even when the
correct binding mode was found.

### 3PTB — benzamidine in trypsin

A small, stiff ligand: the engine must nail it, and it does.

* crystal pose scores {trypsin.crystal_affinity:.3f} kcal/mol
* best pose scores {trypsin.best_affinity:.3f} kcal/mol
* N_tors = {trypsin.num_tors:g}, {trypsin.receptor_atoms} receptor atoms,
  grid {trypsin.grid_points} points
* {trypsin.elapsed:.1f} s

Benzamidine is *chemically* planar — an aromatic ring fused to an amidine.
Its coordinates are nevertheless three-dimensional (`odock prepare ligand`
prints the out-of-plane extent), and no docking result depends on the shape of
the molecule being "3-D" or "flat"; what matters is that the coordinates are
real, which is what the planarity figure verifies.

### 1M17 — erlotinib in EGFR

A deliberately harder case: 29 heavy atoms and 11 rotatable bonds, i.e. a
13-dimensional search space over a 4 500 Å³ box, and a binding mode that in the
crystal is partly water-mediated (the waters are stripped by default).

The top-scoring pose is {egfr.best_rmsd:.2f} Å from the crystal pose, but the
correct binding mode **is** in the output: it is the pose at
**{egfr.closest_within():.2f} Å**, ranked below the top because the first four
poses lie within {max(egfr_rows) - min(egfr_rows):.2f} kcal/mol of one another. That is the honest
picture — the search finds the experimental pose, and the empirical force field
cannot rank it first for a molecule with 11 rotatable bonds. The same run
reproduces the crystal pose to {trypsin.closest_within():.2f} Å for the rigid ligand above,
which is what makes the erlotinib case a force-field limit rather than an engine
bug. Remember also that the crystallographic waters are stripped by default and
that erlotinib's binding mode is partly water-mediated.

## Files

| path | contents |
|---|---|
| `3ptb/receptor.pdbqt`, `3ptb/ligand.pdbqt` | prepared inputs |
| `3ptb/box.json` | **the active site of the 3PTB run** (centre, size, spacing) |
| `3ptb/poses.pdbqt` | the docked poses (multi-model PDBQT) |
| `egfr/receptor.pdbqt`, `egfr/ligand.pdbqt`, `egfr/poses.pdbqt` | the same for EGFR |
| `egfr/box.json` | the active site of the EGFR run |
| `ligand_from_smiles.pdbqt`, `.smi` | a ligand built from a SMILES alone |
| `library.smi` | a 17-molecule screening library for `3ptb/box.json` — hand-written and checked in, **not** produced by this script; see `docs/SCREENING.md` |

## Where the structures came from

* `3PTB` — benzamidine·bovine trypsin (RCSB), receptor and ligand split from the
  crystal file; 62 water atoms dropped.
* `1M17` — erlotinib·EGFR kinase domain (RCSB); the `AQ4` residue is the ligand,
  and its bond orders are restored from the SMILES shown in
  `examples/make_demo.py` because a PDB file carries none.
"""
    (outdir / "3ptb" / "result.json").write_text(
        json.dumps(trypsin.as_dict(), indent=1), encoding="utf-8"
    )
    (outdir / "egfr" / "result.json").write_text(
        json.dumps(egfr.as_dict(), indent=1), encoding="utf-8"
    )
    (outdir / "README.md").write_text(readme, encoding="utf-8")
    print()
    print(f"wrote {outdir / 'README.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
